name = "philan-net"
type = "webpack"
webpack_config = "workers-site/webpack.config.js"
account_id = "020f099028cabbcf02f27b4e6b39cbfc"
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./public"
entry-point = "./workers-site"
