name = "philan-net"
type = "webpack"
webpack_config = "workers-site/webpack.config.js"
account_id = "020f099028cabbcf02f27b4e6b39cbfc"
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [
	 { binding = "USERS", preview_id = "b66d3106391e41bc97c977d1d9cb06bc" }
]
[site]
bucket = "./public"
entry-point = "./workers-site"
